services:
  configserver:
    image: "romasko/configserver:s4" #You need to change this to your Docker Hub username
    container_name: configserver-microservice
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - banking-network

  accounts:
    image: "romasko/accounts:s4" #You need to change this to your Docker Hub username
    container_name: accounts-microservice
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - banking-network
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default

  loans:
    image: "romasko/loans:s4" #You need to change this to your Docker Hub username
    container_name: loans-microservice
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - banking-network
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
  cards:
    image: "romasko/cards:s4" #You need to change this to your Docker Hub username
    container_name: cards-microservice
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - banking-network
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
networks:
  banking-network:
    driver: "bridge"